version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - 80:80
    depends_on:
      - web_app
  web_app:
    image: web_app
    build:
      context: ./web
    container_name: "web_cont"
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=nam123456
      - DB_NAME=test_db
    depends_on:
      - db
  db:
    image: mysql
    container_name: "db_cont"
    environment:
      - MYSQL_ROOT_PASSWORD=nam123456
      - MYSQL_DATABASE=test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql
